# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600c85a3b368ad729d6c1346cab45b072e63052de9d89eb3a6e4b528075fab8f1c33d39ee583323915a689d8d5b9b5839e49dcd76955615f4ab24624244e60fe

test:
  secret_key_base: cf52408e481b3ea463cf99e7411c9e7e7f68bc69105fdaa9344707cfbced534328765d0da0db2b8a60377a4d9d1d6a6609aa48dc52987793bfcf790c636d1541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
